language: android
dist: trusty
android:
  components:
    - build-tools-29.0.3
    - android-29

script:
  - ./gradlew :librarycielolinkpagamentos:clean :librarycielolinkpagamentos:assembleRelease

deploy:
  provider: script
  script: ./gradlew :librarycielolinkpagamentos:bintrayUpload
  on:
    tags: true